advertisedIP: "100.64.154.246"
dhcpListenAddress: ":67"
extendedHTTPListenAddress: ":15256"
grpcListenAddress: ":15257"
oidcClientID: myoidcclientid
oidcIssuer: https://pojntfx.eu.auth0.com/
proxyDHCPListenAddress: ":4011"
pureConfig: false
tftpListenAddress: ":69"
workingDir: /home/pojntfx/.local/share/bofied/var/lib/bofied
starterURL: https://github.com/pojntfx/ipxe-binaries/releases/download/latest/ipxe.tar.gz
skipStarterDownload: false
