workingDir: /home/pojntfx/.local/share/bofied/var/lib/bofied
bootConfigFileName: config.go
advertisedIP: "100.64.154.246"
dhcpListenAddress: ":67"
proxyDHCPListenAddress: ":4011"
tftpListenAddress: ":69"
webDAVListenAddress: ":15256"
httpListenAddress: ":15257"
oidcClientID: myoidcclientid
oidcIssuer: https://pojntfx.eu.auth0.com/
